[package]
name = "moon_calendar"
version = "0.1.0"
authors = ["kirila menski"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
chrono = "*"